// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parcial2_LondonoValenciaSebastian.DAL;

#nullable disable

namespace Parcial2_LondonoValenciaSebastian.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Parcial2_LondonoValenciaSebastian.DAL.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntranceGate")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ddd3fbdb-fb96-42c6-8fca-fbce4384feb3"),
                            IsUsed = false
                        },
                        new
                        {
                            Id = new Guid("b6aefdbb-682f-41fa-9094-bfc700334190"),
                            IsUsed = false
                        },
                        new
                        {
                            Id = new Guid("24d3e3e2-74c4-425b-90f8-89ad29b0abbd"),
                            IsUsed = false
                        },
                        new
                        {
                            Id = new Guid("36c45637-b123-467e-a588-b96329972fe9"),
                            IsUsed = false
                        },
                        new
                        {
                            Id = new Guid("93f0d2f7-1206-4023-9aed-6eaba04bba16"),
                            IsUsed = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
